version: 2
jobs:
  build:
    docker:
      - image: 218546966473.dkr.ecr.us-east-1.amazonaws.com/circle-ci:tap-tester-v4
    steps:
      - checkout
      - run:
          name: 'Setup virtual env'
          command: |
            pyenv global 3.6.9
            pyenv rehash
            pip install awscli
            python3 -mvenv /usr/local/share/virtualenvs/tap-nikabot
            source /usr/local/share/virtualenvs/tap-nikabot/bin/activate
            pip install -U 'pip<19.2' setuptools
            pip install .[dev]
      - run:
          name: 'pylint'
          command: |
            source /usr/local/share/virtualenvs/tap-nikabot/bin/activate
            make lint
      #TODO: Unit tests failing in circle but pass locally, if contributer helps explain it would be nice to fix these
      #- run:
      #    name: 'unit-tests'
      #    command: |
      #      source /usr/local/share/virtualenvs/tap-nikabot/bin/activate
      #      make test

workflows:
  version: 2
  commit:
    jobs:
      - build:
          context: circleci-user
  build_daily:
    triggers:
      - schedule:
          cron: "0 0 * * *"
          filters:
            branches:
              only:
                - master
    jobs:
      - build:
          context: circleci-user
